# Generated by Django 5.2.4 on 2025-07-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_remove_vendor_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('high_value_orders', models.IntegerField(default=0)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.vendor')),
            ],
        ),
    ]
